//
//  TextManager.swift
//  HiShopSale
//
//  Created by Bee_MacPro on 21/05/2021.
//

import UIKit

extension TextManager {
    static let search                               = "Tìm kiếm"
    static let shopName                             = "Tên shop"
    static let shopNamePlaceholder                  = "Nhập tên shop"
    static let shopPhone                            = "Số điện thoại"
    static let shopPhonePlaceholder                 = "Nhập số điện thoại"
    static let addressDetail                        = "Địa chỉ liên hệ"
    static let addressDetailPlaceholder             = "Nhập địa chỉ liên hệ"
    static let shopAddressTitle                     = "Địa chỉ liên hệ"
    static let shopAddress                          = "Nhập địa chỉ liên hệ"
    static let provinceCity                         = "Tỉnh/Thành Phố"
    static let district                             = "Quận/Huyện"
    static let ward                                 = "Xã/Phường"
    static let apartmentNumberStreet                = "Số nhà, đường"
    
    static let signInShop                           = "Đăng nhập với Hi SHOP"
    static let signIn                               = "Đăng nhập"
    static let signUp                               = "Đăng ký"
    static let signUpShop                           = "Đăng ký và tạo Shop"
    static let username                             = "Tên đăng nhập"
    static let enterUsername                        = "Email đăng nhập"
    static let email                                = "Email"
    static let emailPlaceHolder                     = "Nhập email"
    static let password                             = "Mật khẩu"
    static let enterPassword                        = "Nhập mật khẩu"
    static let changePassword                       = "Đổi mật khẩu"
    static let forgotPassword                       = "Quên mật khẩu"
    static let welcomeShop                          = "Chào mừng bạn đến Hi Shop"
    static let forgotPW                             = "Quên mật khẩu"
    static let next                                 = "Tiếp tục"
    static let hotline                              = "Hotline"
    static let hotlinePlaceholder                   = "Nhập Hotline"
    static let linkGGMap                            = "Link google map"
    static let linkGGMapPlaceholder                 = "Nhập link google map"
    static let linkWebsite                          = "Link website"
    static let linkWebsitePlaceHolder               = "Nhập link website"
    static let yourCode                             = "Mã code"
    static let resendCodeAgain                      = "Bạn không nhận được mã code?"
    static let againCode                            = "Thử lại"
    static let verifyCode                           = "Xác thực tài khoản"
    static let createNewPW                          = "Tạo mật khẩu mới"
    static let confirmPW                            = "Nhập lại mật khẩu"
    static let preview                              = "Xem trước"
    static let photoPermission                      = "Cho phép ứng dụng truy cập thư viện ảnh để chia sẻ hình ảnh đến bạn bè"
    static let cameraPermission                     = "Cho phép ứng dụng truy cập Camera ảnh để chia sẻ khoảnh khắc đến bạn bè"
    static let edit                                 = "Sửa"
    static let done                                 = "Xong"
    static let searchProduct                        = "Tìm kiếm sản phẩm"
    static let emptyProducts                        = "Không có sản phẩm nào"
    static let invalidEmail                         = "Email không hợp lệ. Bạn vui lòng kiểm tra lại!"
    static let statusLogOut                         = "Bạn có chắc chắn muốn đăng xuất?"
    static let updateAvatar                         = "Cập nhật đại diện"
    static let viewAvatar                           = "Xem ảnh đại diện"
    static let noPreview                            = "Không có bản xem trước nào"
    static let supCateogry                          = "Danh mục cha"
    static let subCateogry                          = "Danh mục con"
    static let detailProduct                        = "Thông tin chi tiết"
    static let comment                              = "Bình luận"
    static let changePW                             = "Đổi mật khẩu"
    static let productDiscover                      = "Khám phá thêm"
    static let inputComment                         = "Thêm bình luận"
    static let seemore                              = "Xem thêm"
    static let createCommentSuccess                 = "Thêm bình luận thành công"
    static let replyCommentSuccess                  = "Trả lời bình luận thành công"
    static let notification                         = "Thông báo"
    static let deleteProduct                        = "Bạn có chắc muốn xoá sản phẩm"
    static let whatDoYouWantToView                  = "Bạn muốn thấy gì?"
    static let confirm                              = "Xác nhận"
    static let emptyOrder                           = "Bạn chưa có đơn hàng nào"
    static let addressOrder                         = "Địa chỉ người nhận"
    static let transportOrder                       = "Hình thức giao hàng"
    static let paymentOrder                         = "Hình thức thanh toán"
    static let infoOrder                            = "Thông tin kiện hàng"
    static let biller                               = "Hoá đơn"
    static let orderCode                            = "Mã đơn hàng:"
    static let orderTime                            = "Ngày đặt hàng:"
    static let deliveryTime                         = "Giao hàng"
    static let expectDelivery                       = "Tạm tính"
    static let shippingFee                          = "Phí vận chuyển"
    static let titleTotalMoney                      = "Tổng cộng"
}
